bump_version: null
lint:
  subworkflow_changes: false
nf_core_version: 3.0.1
org_path: null
repository_type: pipeline
template:
  author: "Louis Le Nezet, Anabella Trigilla"
  description: Phasing and imputation pipeline
  force: false
  is_nfcore: true
  name: phaseimpute
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.1dev
update: null
