name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors

on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

env:
  NXF_ANSI_LOG: false
  NFTEST_VER: "0.9.0"

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run nf-test with standard profiles
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/phaseimpute') }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        NXF_VER:
          - "24.04.2"
          - "latest-everything"
        TEST_PROFILE:
          - "test_all"
          - "test_validate"
          - "test_stitch"
          - "test_dog"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash -s $NFTEST_VER
          sudo mv nf-test /usr/local/bin/

      - name: Disk space cleanup
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Run pipeline with test data (docker)
        # TODO nf-core: You can customise CI pipeline run tests as required
        # For example: adding multiple test runs with different parameters
        # Remember that you can parallelise this by using strategy.matrix
        run: |
          nf-test test --tag "${{ matrix.TEST_PROFILE }}" --profile docker --outdir ./results

      - name: Run pipeline with test data (singularity)
        # TODO nf-core: You can customise CI pipeline run tests as required
        run: |
          nf-test test --tag "${{ matrix.TEST_PROFILE }}" --profile singularity --outdir ./results
        if: "${{ github.base_ref == 'master' }}"

      - name: Run pipeline with test data (conda)
        # TODO nf-core: You can customise CI pipeline run tests as required
        run: |
          nf-test test --tag "${{ matrix.TEST_PROFILE }}" --profile conda --outdir ./results
        if: "${{ github.base_ref == 'master' }}"
